pipeline:
  service:
    log_level: info
    flush: 5
    http_server: on
    http_listen: 0.0.0.0
    http_port: 2020
    parsers_file: /fluent-bit/etc/parsers.conf

  inputs:
    # Monitorar eventos do Docker daemon em tempo real
    # Docs: https://docs.fluentbit.io/manual/data-pipeline/inputs/docker-events
    # Captura: create, start, stop, die, build, destroy, etc
    - name: docker_events
      tag: docker.events
      unix_path: /var/run/docker.sock
      buffer_size: 32768
      parser: json
      threaded: true
      reconnect.retry_interval: 1
      reconnect.retry_limits: 5

    # Coletar métricas de containers em tempo real
    # Docs: https://docs.fluentbit.io/manual/data-pipeline/inputs/docker-metrics
    # Captura: CPU %, memória, I/O de disco e rede
    - name: docker_metrics
      tag: docker.metrics
      interval_sec: 5
      path.containers: /var/lib/docker/containers
      path.sysfs: /sys/fs/cgroup
      threaded: true

    # Monitorar logs do próprio Fluent Bit
    - name: tail
      path: /fluent-bit/var/log/fluent-bit.log
      tag: docker.fluentbit
      parser: json
      db: /var/log/flb-checkpoint-fluentbit.db

  filters:
    # Enriquecer eventos Docker com contexto
    - name: record_modifier
      match: docker.events
      record:
        cluster: docker-local
        environment: development
        monitored_by: fluent-bit
        data_type: event

    # Processar métricas com script Lua para alertas inteligentes
    - name: lua
      match: docker.metrics
      script: /fluent-bit/scripts/docker-health.lua
      call: cb_filter
      protected_mode: true

    # Enriquecer métricas com contexto
    - name: record_modifier
      match: docker.metrics
      record:
        cluster: docker-local
        environment: development
        monitored_by: fluent-bit
        data_type: metrics

  outputs:
    # Enviar todos os eventos e métricas para OpenSearch
    - name: opensearch
      match: 'docker.*'
      host: ${OPENSEARCH_HOST}
      port: ${OPENSEARCH_PORT}
      http_user: ${OPENSEARCH_USER}
      http_passwd: ${OPENSEARCH_PASSWD}
      index: docker-monitoring
      logstash_format: on
      logstash_prefix: docker
      suppress_type_name: on
      tls: on
      tls.verify: off
      retry_limit: false
      buffer.type: filesystem
      buffer.path: /var/log/flb-storage-docker/

    # Debug: stdout
    - name: stdout
      match: 'docker.*'
      format: json_lines
