# Pipeline Básico: HTTP Source → Mutate → OpenSearch Sink
# Descrição: Receber logs JSON via HTTP e armazenar no OpenSearch
# Endpoint: POST http://localhost:21000/log/ingest
# Formato: Array JSON de eventos

log-ingestion-pipeline:
  workers: 4
  delay: 50
  # ========== SOURCE: Receber logs via HTTP ==========
  source:
    http:
      # Porta de escuta
      port: 21000

      # Caminho da API
      path: "/log/ingest"

  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 8

  # ========== PROCESSOR: Enriquecer eventos ==========
  processor:
    
    - date:
        from_time_received: true
        destination: "@timestamp"

    - add_entries:
        entries:
          - key: "another_field"
            format: "${component}"

    # - anomaly_detector:
    #    keys: ["latency"]
    #     mode:
    #        random_cut_forest:

    - obfuscate:
        source: "phone"
    
    
  # ========== SINK: Armazenar no OpenSearch ==========
  sink:
    - stdout:

    - opensearch:
        # Endpoints do cluster OpenSearch
        hosts: ["https://192.168.1.200:9200"]
        username: "admin"
        password: "Admin#123456"

        # Modo inseguro: desabilita validação SSL (APENAS DEV!)
        insecure: true

        # Índice de destino com padrão de data
        # Cria: logs-app-2025.01.15
        index: "logs-app-%{yyyy.MM.dd}"

        # Tipo de documento
        # document_type: "_doc"

        # Buffer de bulk para performance
        bulk_size: 500

        # Flush automático a cada X segundos
        #flush_interval: 30

        # Número de tentativas de reconexão
        max_retries: 3
