# Pipeline Básico: HTTP Source → Mutate → OpenSearch Sink
# Descrição: Receber logs JSON via HTTP e armazenar no OpenSearch
# Endpoint: POST http://localhost:21000/log/ingest
# Formato: Array JSON de eventos

log-ingestion-pipeline:
  workers: 4
  delay: 50
  # ========== SOURCE: Receber logs via HTTP ==========
  source:
    http:
      # Porta de escuta
      port: 21000

      # Caminho da API
      path: "/log/ingest"

  buffer:
    bounded_blocking:
      buffer_size: 512
      batch_size: 8

  # ========== PROCESSOR: Enriquecer eventos ==========
  processor:
    
    - date:
        from_time_received: true
        destination: "@timestamp"
        
    - add_entries:
        entries:
          - key: "another_field"
            format: "${component}"

    #- anomaly_detector:
    #    keys: ["latency"]
    #    mode:
    #      random_cut_forest:

    - obfuscate:
        source: "phone"
    
    
  # ========== SINK: Armazenar no OpenSearch ==========
  sink:
    - opensearch:
        # Endpoints do cluster OpenSearch
        hosts: ["https://192.168.1.200:9200"]
        username: "admin"
        password: "Admin#123456"
        insecure: true
        index: "logs-app-%{yyyy.MM.dd}"
        bulk_size: 500
        max_retries: 3

    - stdout:
