status = info
name = DataPrepperRollingFileConfig

appenders = console

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} [%t] %-5p %40C - %m%n

rootLogger.level = debug
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.file.ref = RollingFile
logger.pipeline.name = org.opensearch.dataprepper.pipeline
logger.pipeline.level = debug
logger.parser.name = org.opensearch.dataprepper.parser
logger.parser.level = debug
logger.plugins.name = org.opensearch.dataprepper.plugins
logger.plugins.level = debug
